# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/Desktop/lab_5_processor/lab_5_processor.srcs/sources_1/ip/dMem/dMem.xci
# IP: The module: 'dMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/Desktop/lab_5_processor/lab_5_processor.gen/sources_1/ip/dMem/dMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dMem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user/Desktop/lab_5_processor/lab_5_processor.srcs/sources_1/ip/dMem/dMem.xci
# IP: The module: 'dMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/Desktop/lab_5_processor/lab_5_processor.gen/sources_1/ip/dMem/dMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dMem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
