#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Feb 23 22:08:56 EST 2026
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 4d2d5afc9f07415bb90cc6febba084eb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot fancy_counter_tb_behav xil_defaultlib.fancy_counter_tb -log elaborate.log"
xelab -wto 4d2d5afc9f07415bb90cc6febba084eb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot fancy_counter_tb_behav xil_defaultlib.fancy_counter_tb -log elaborate.log

