#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 23 18:34:35 EST 2026
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim fancy_counter_tb_behav -key {Behavioral:sim_1:Functional:fancy_counter_tb} -tclbatch fancy_counter_tb.tcl -log simulate.log"
xsim fancy_counter_tb_behav -key {Behavioral:sim_1:Functional:fancy_counter_tb} -tclbatch fancy_counter_tb.tcl -log simulate.log

