#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jan 22 20:18:02 EST 2026
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim lab_intro_tb_time_impl -key {Post-Implementation:sim_1:Timing:lab_intro_tb} -tclbatch lab_intro_tb.tcl -view /home/user/Desktop/lab_intro/lab_intro_tb_behav.wcfg -log simulate.log"
xsim lab_intro_tb_time_impl -key {Post-Implementation:sim_1:Timing:lab_intro_tb} -tclbatch lab_intro_tb.tcl -view /home/user/Desktop/lab_intro/lab_intro_tb_behav.wcfg -log simulate.log

