#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Feb 27 16:21:16 EST 2026
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto f9cb581a06be4b0baf961d8df267a20b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ripple_adder_tb_behav xil_defaultlib.ripple_adder_tb -log elaborate.log"
xelab -wto f9cb581a06be4b0baf961d8df267a20b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ripple_adder_tb_behav xil_defaultlib.ripple_adder_tb -log elaborate.log

