#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Apr 29 13:50:21 EDT 2026
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 3543c09b47cb4c12b9ea623fb85e7976 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot spi_master_tb_behav xil_defaultlib.spi_master_tb -log elaborate.log"
xelab -wto 3543c09b47cb4c12b9ea623fb85e7976 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot spi_master_tb_behav xil_defaultlib.spi_master_tb -log elaborate.log

