#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Apr 29 13:50:22 EDT 2026
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim spi_master_tb_behav -key {Behavioral:sim_1:Functional:spi_master_tb} -tclbatch spi_master_tb.tcl -log simulate.log"
xsim spi_master_tb_behav -key {Behavioral:sim_1:Functional:spi_master_tb} -tclbatch spi_master_tb.tcl -log simulate.log

