#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Jan 22 19:52:12 EST 2026
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 382d46cc1c7247108113bef65b5587f9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot lab_intro_tb_behav xil_defaultlib.lab_intro_tb -log elaborate.log"
xelab -wto 382d46cc1c7247108113bef65b5587f9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot lab_intro_tb_behav xil_defaultlib.lab_intro_tb -log elaborate.log

